/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * Run `pnpm gen:agentic` to regenerate.
 */

export type paths = Record<string, never>
export type components = { schemas: Record<string, never> }
export type operations = Record<string, never>
