/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invoke */
        post: operations["invoke_invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream */
        post: operations["stream_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/agui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Agui */
        post: operations["stream_agui_stream_agui_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_rag_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_agents_get"];
        put?: never;
        /** Register Agent */
        post: operations["register_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orchestrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Orchestrate */
        post: operations["orchestrate_orchestrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{thread_id}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pending */
        get: operations["get_pending_sessions__thread_id__pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{thread_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_sessions__thread_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{thread_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_sessions__thread_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityMessage
         * @description An activity progress message emitted between chat messages.
         */
        ActivityMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "activity";
            /** Activitytype */
            activityType: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** AgentInfo */
        AgentInfo: {
            /** Name */
            name: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Agent Name
             * @default default
             */
            agent_name: string;
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /**
         * AssistantMessage
         * @description An assistant message.
         */
        AssistantMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "assistant";
            /** Content */
            content?: string | null;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCall"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BinaryInputContent
         * @description A binary payload reference in a multimodal user message.
         */
        BinaryInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Mimetype */
            mimeType: string;
            /** Id */
            id?: string | null;
            /** Url */
            url?: string | null;
            /** Data */
            data?: string | null;
            /** Filename */
            filename?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Context
         * @description Additional context for the agent.
         */
        Context: {
            /** Description */
            description: string;
            /** Value */
            value: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * DeveloperMessage
         * @description A developer message.
         */
        DeveloperMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "developer";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * FunctionCall
         * @description Name and arguments of a function call.
         */
        FunctionCall: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /** Texts */
            texts: string[];
        };
        /** IngestResponse */
        IngestResponse: {
            /** Ids */
            ids: string[];
        };
        /** InvokeRequest */
        InvokeRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /** InvokeResponse */
        InvokeResponse: {
            /** Content */
            content: string;
        };
        /** OrchestrateRequest */
        OrchestrateRequest: {
            /** Task */
            task: string;
            /**
             * Agent Name
             * @default default
             */
            agent_name: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /**
         * ReasoningMessage
         * @description A reasoning message containing the agent's internal reasoning process.
         */
        ReasoningMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "reasoning";
            /** Content */
            content: string;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RegisterAgentRequest */
        RegisterAgentRequest: {
            /** Name */
            name: string;
            /** System Prompt */
            system_prompt?: string | null;
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
            /** Model Name */
            model_name?: string | null;
        };
        /** RejectRequest */
        RejectRequest: {
            /**
             * Agent Name
             * @default default
             */
            agent_name: string;
            /**
             * User Id
             * @default default
             */
            user_id: string;
            /**
             * Reason
             * @default User rejected tool call
             */
            reason: string;
        };
        /**
         * RunAgentInput
         * @description Input for running an agent.
         */
        RunAgentInput: {
            /** Threadid */
            threadId: string;
            /** Runid */
            runId: string;
            /** Parentrunid */
            parentRunId?: string | null;
            /** State */
            state: unknown;
            /** Messages */
            messages: (components["schemas"]["DeveloperMessage"] | components["schemas"]["SystemMessage"] | components["schemas"]["AssistantMessage"] | components["schemas"]["UserMessage"] | components["schemas"]["ToolMessage"] | components["schemas"]["ActivityMessage"] | components["schemas"]["ReasoningMessage"])[];
            /** Tools */
            tools: components["schemas"]["Tool"][];
            /** Context */
            context: components["schemas"]["Context"][];
            /** Forwardedprops */
            forwardedProps: unknown;
        } & {
            [key: string]: unknown;
        };
        /**
         * SystemMessage
         * @description A system message.
         */
        SystemMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TextInputContent
         * @description A text fragment in a multimodal user message.
         */
        TextInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Tool
         * @description A tool definition.
         */
        Tool: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolCall
         * @description A tool call, modelled after OpenAI tool calls.
         */
        ToolCall: {
            /** Id */
            id: string;
            /**
             * Type
             * @default function
             * @constant
             */
            type: "function";
            function: components["schemas"]["FunctionCall"];
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolMessage
         * @description A tool result message.
         */
        ToolMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /** Content */
            content: string;
            /** Toolcallid */
            toolCallId: string;
            /** Error */
            error?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * UserMessage
         * @description A user message supporting text or multimodal content.
         */
        UserMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "user";
            /** Content */
            content: string | (components["schemas"]["TextInputContent"] | components["schemas"]["BinaryInputContent"])[];
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    invoke_invoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_agui_stream_agui_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_rag_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_agent_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orchestrate_orchestrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrchestrateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_sessions__thread_id__pending_get: {
        parameters: {
            query?: {
                agent_name?: string;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_sessions__thread_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_sessions__thread_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
